### ISSUE TITLE
Grouper les field_keys et stage_keys par pipeline

### ISSUE THREAD

**Issue by sunny** [KissKissBankBank/streaker#13]
Les field keys (`first_name: 1004`) on des identifiants uniques par pipeline. Du coup il serait intéressant dans la configuration de les séparer de la même façon. Exemple :

Avant : 

```rb
  config.pipeline_keys = {
    default: 'some_pipeline_key',
    other: 'some_other_pipeline_key',
  }

  config.stage_keys = {
    default: 33333,
    other_default: 33334,
  }

  config.field_keys = {
    first_name: 1043,
    other_phone: 1043,
  }
```

Après : 

```rb
  config.pipeline_keys = {
    default: 'some_pipeline_key',
    other: 'some_other_pipeline_key',
  }

  config.stage_keys = {
    default: {
      default: 33333,
    },
    other: {
      default: 33334,
    },
  }

  config.field_keys = {
    default: {
      first_name: 1043,
    },
    other: {
      phone: 1043,
    } 
  }
```

CC @williampollet @LanF3usT

**Comment by williampollet** [comment]
J'aime le concept. Ensuite est ce que l'on n'en profiterait pas pour commencer à réfléchir à comment appliquer la philo de rails convention > configuration? Ca rendrait la gem super scalable non?

**Comment by sunny** [comment]
Carrément. Mais je vois mal comment tu peux te passer de cette configuration pour trouver les bonnes clefs. Peut-être avec de l'introspection (chercher le champ par son nom, par exemple) ?

**Comment by williampollet** [comment]
J'ai re réfléchi, et en fait on est dans le cas typique du fichier de config je crois:  
 - est ce qu'on pourrait pas laisser l'API key dans l'initializer  (données sensibles)
 - mettre le reste (les fields) dans un fichier de config.yml (comme le circle.yml) ?

**Comment by sunny** [comment]
Oui, carrément quand ça commence à faire un fichier ruby un peu trop long ça peut être bien d'en faire un `yml`, ça fait moins de code. Du coup il serait rangé à peu près de la même façon, non ?

```yml
stage_keys:
  default_stage:
    default: 3001
  my_other_stage:
    default: 3001

field_keys:
  default_stage:
     my_first_name: 1001
  my_other_stage:
    my_phone: 1001

dropdown_value_keys:
  default_stage:
    my_field:
      my_value_one: 9001
      my_value_two: 9002
  my_other_stage:
    my_phone_prefix:
      my_example_value_one: 9001
      my_example_value_two: 9002
```

**Comment by sunny** [comment]
Ou, peut-être, inverser la configuration.

```yml
pipelines:

  default:
    key: 3001

    fields:
      firstname:
        key: 1001
      lastname:
        key: 1002
      country:
        key: 1004
        values:
          fr: 9001
          en: 9002
          es: 9003

  other_pipeline:
    fields:
      phone_prefix:
        key: 1001
```
